"""
CreditPulse360 - Interactive Demo
An AI-powered Financial Health Score for credit-invisible, New-to-Bank MSMEs.

IMPORTANT: This demo runs entirely on SYNTHETIC data generated by
data/generate_data.py. It illustrates the scoring methodology, model,
and explainability layer end-to-end. It is NOT connected to real
GSTN / UPI / Account Aggregator systems.
"""

import joblib
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

st.set_page_config(page_title="CreditPulse360", page_icon="\U0001F4B0", layout="wide")

TEAL = "#0F6B4C"
ORANGE = "#E2711D"
NAVY = "#1B2A4A"


@st.cache_resource
def load_model():
    return joblib.load("model/creditpulse_model.pkl")


@st.cache_data
def load_data():
    return pd.read_csv("data/msme_synthetic_dataset.csv")


def score_to_band(score):
    if score >= 700:
        return "Low", TEAL, "Auto-approve"
    elif score >= 550:
        return "Medium", ORANGE, "Refer to RM"
    else:
        return "High", "#C0392B", "Decline / Re-assess"


def recommended_line(score, avg_inflow):
    if score < 550:
        return 0
    multiplier = np.clip((score - 550) / 350, 0.1, 1.0)
    return round(avg_inflow * 30 * multiplier * 3, -3)  # rough heuristic, ~3x monthly inflow scaled by risk


bundle = load_model()
model = bundle["model"]
explainer = bundle["explainer"]
FEATURES = bundle["features"]
FEATURE_LABELS = bundle["feature_labels"]
TEST_AUC = bundle["test_auc"]

df = load_data()
X = df[FEATURES]
proba = model.predict_proba(X)[:, 1]
df["default_probability"] = proba
df["financial_health_score"] = (900 - proba * 600).round().astype(int)
df["risk_band"] = df["financial_health_score"].apply(lambda s: score_to_band(s)[0])

st.markdown(f"""
<div style="background:{NAVY};padding:18px 26px;border-radius:8px;margin-bottom:18px;">
  <h2 style="color:white;margin:0;">CreditPulse360</h2>
  <p style="color:#CBD5C0;margin:4px 0 0 0;">AI-powered Financial Health Score for credit-invisible, New-to-Bank MSMEs
  &nbsp;|&nbsp; <em>Synthetic-data prototype &middot; Model test AUC: {TEST_AUC:.2f}</em></p>
</div>
""", unsafe_allow_html=True)

tab1, tab2 = st.tabs(["\U0001F4CA Underwriter Portfolio View", "\U0001F50D Applicant Score Explorer"])

# ---------------- Portfolio View ----------------
with tab1:
    st.subheader("Batch: Synthetic NTB MSME Portfolio")

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("MSMEs scored", len(df))
    c2.metric("Auto-approve (Low risk)", int((df.risk_band == "Low").sum()))
    c3.metric("Refer to RM (Medium)", int((df.risk_band == "Medium").sum()))
    c4.metric("Decline (High risk)", int((df.risk_band == "High").sum()))

    sector_filter = st.multiselect("Filter by sector", sorted(df.sector.unique()))
    band_filter = st.multiselect("Filter by risk band", ["Low", "Medium", "High"])

    view = df.copy()
    if sector_filter:
        view = view[view.sector.isin(sector_filter)]
    if band_filter:
        view = view[view.risk_band.isin(band_filter)]

    view["recommended_line_inr"] = view.apply(
        lambda r: recommended_line(r.financial_health_score, r.upi_avg_daily_inflow), axis=1
    )

    st.dataframe(
        view[["applicant_id", "business_name", "sector", "vintage_months",
              "financial_health_score", "risk_band", "recommended_line_inr"]]
        .sort_values("financial_health_score", ascending=False)
        .rename(columns={
            "applicant_id": "ID", "business_name": "MSME", "sector": "Sector",
            "vintage_months": "Vintage (mo)", "financial_health_score": "FH Score",
            "risk_band": "Risk Band", "recommended_line_inr": "Recommended Line (INR)"
        }),
        use_container_width=True, height=420,
    )

# ---------------- Applicant Detail ----------------
with tab2:
    applicant_id = st.selectbox("Select an MSME applicant", df.applicant_id)
    row = df[df.applicant_id == applicant_id].iloc[0]
    score = int(row.financial_health_score)
    band, color, action = score_to_band(score)

    left, right = st.columns([1, 1.4])

    with left:
        fig = go.Figure(go.Indicator(
            mode="gauge+number",
            value=score,
            number={"suffix": " / 900"},
            gauge={
                "axis": {"range": [300, 900]},
                "bar": {"color": color},
                "steps": [
                    {"range": [300, 550], "color": "#FADBD8"},
                    {"range": [550, 700], "color": "#FDEBD0"},
                    {"range": [700, 900], "color": "#D5F0E3"},
                ],
            },
            title={"text": f"{row.business_name}<br><span style='font-size:0.8em'>{row.sector}</span>"},
        ))
        fig.update_layout(height=320, margin=dict(t=60, b=10, l=20, r=20))
        st.plotly_chart(fig, use_container_width=True)

        st.markdown(f"**Risk Band:** :{'green' if band=='Low' else 'orange' if band=='Medium' else 'red'}[{band}]")
        st.markdown(f"**Recommended Action:** {action}")
        if score >= 550:
            line = recommended_line(score, row.upi_avg_daily_inflow)
            st.markdown(f"**Suggested Working Capital Line:** \u20B9{line:,.0f}")

    with right:
        st.markdown("**Top Reason Codes (SHAP-based, model-derived)**")
        shap_values = explainer.shap_values(X[X.index == row.name])
        contributions = pd.Series(shap_values[0], index=FEATURES)
        top = contributions.reindex(contributions.abs().sort_values(ascending=False).index).head(6)

        reason_rows = []
        for feat, val in top.items():
            direction = "Increases risk" if val > 0 else "Reduces risk"
            reason_rows.append({
                "Factor": FEATURE_LABELS[feat],
                "Applicant Value": round(row[feat], 3),
                "Effect": direction,
            })
        st.table(pd.DataFrame(reason_rows))

        st.caption(
            "Reason codes are derived directly from the trained model's SHAP values for this "
            "applicant \u2014 not hardcoded \u2014 satisfying explainable-AI / fair-lending requirements."
        )

st.divider()
st.caption(
    "\u26A0\uFE0F Demo notice: all applicant data on this page is synthetically generated "
    "(see data/generate_data.py) to illustrate the scoring pipeline. No real GSTN, UPI, or "
    "Account Aggregator data is used. See README.md for the production integration roadmap."
)
